### ISSUE TITLE
loader throws an error not found

### ISSUE THREAD

**Issue by streamly** [12vanblart/firebase-example#1]
document.getElementById('loader').style.display = 'none';

what is this loader element? thx

**Comment by TerabyteTiger** [comment]
The loader should be an icon of some kind that Google displays while things are loading/processing, then this line removes it from the UI when the login UI is showing to the user. 

Can you share your full error message?

**Comment by streamly** [comment]
I am now using the code on firebase ui site, but think your code just never referenced the loader. thx
